# ------------------------------------------------------------------------------
# This code was automatically generated by Boo.Lang.CodeDom v.0.9.7.0.
# 
#      Changes to this file may cause incorrect behavior and will be lost if 
#      the code is regenerated.
# ------------------------------------------------------------------------------

import System

namespace AssemblyBoo


class PlatformHelper:
	
	public def constructor():
		pass

